### PR TITLE
Disable bad performers

### PR DESCRIPTION
**Pull request by joesilber**
main features
- option for additional output column to control batch classification of good vs bad positioners
- additional note column to explain rationale and tolerance used (these will get posted to posmovedb as well)

side stuff
- some code cleanup
- use of nominal offset xy positions rather than complicated calcs on metrology
- fit_posparams now keeps hold of DEVICE_LOC, PETAL_ID, PETAL_LOC in its output file

example sequence
```
get_posmoves --host beyonce.lbl.gov --port 5432 --password reader --petal-ids 0 --exposure-ids 3506 --recent-rehome-exposure-ids 3506 -o . -c --pos-ids movers
fit_posparams -i M?????.csv -o .
merge_posparams -i *_fitparams.csv -o merged.csv
prepare_posparams_for_instr -i merged.csv -e
```

### CODE REVIEW

**Comment by julienguy** [comment]
It's not very convenient to use `glob` to get the list of input files instead of the file system.
 At nersc, the current implementation requires we run 
```
merge_posparams -i '*_paramfits.csv' -o merged.csv
```
instead of
```
merge_posparams -i *_paramfits.csv -o merged.csv
```

It could be fixed by removing the call to glob and simply directly getting a list of filenames as an argument if one uses the extra `nargs="*"` in the descriptor of the argument as it was in the previous version. But I guess you changed that to run on windows, so I let you see if there is another solution to find. I'm leaving the PR open for now.

Except for this detail it works fine.
Maybe add a sentence in `prepare_posparams_for_instr --help` explaining what check_static_fit_bounds , check_xy_offsets, check_arm_lengths do. Are these tests against default values and metrology?

**Review by julienguy — CHANGES_REQUESTED** [review]
Suggestion to modify the handling of multiple files in the arguments to the get_posmoves script (see comment).

**Comment by joesilber** [comment]
> 
> 
> Suggestion to modify the handling of multiple files in the arguments to the get_posmoves script (see comment).

I put in a check for Windows, in which case use glob. Otherwsie revert to nargs='*' method.

**Review by julienguy — APPROVED** [review]
thanks

**Pull request merged**
