### PR TITLE
add DEVICE_ID,BUS_ID... to metrology table using online positioner index table.

### PR DESCRIPTION
**Pull request by julienguy**
Use a copy of the online positioner index table to get the device_id and bus_id of positioners in the metrology table for the Mayall focal plane.
Ideally we would get the latest version using the online code but this would add a complex dependency and we are not going to change often positioners or fiducials. When this happens we will also have to change the metrology values, and the way we save configurations.

### CODE REVIEW

**Comment by sbailey** [comment]
Where did `desi_positioner_indexes.csv` come from?  If it is a literal copy of a file from somewhere else, please document that in the README.rst.  If it isn't a literal unchanged copy from elsewhere, some thoughts for consideration:
  * do you really want to include the ENABLED column, since that could be changing semi-frequently?
  * consider dropping the letter prefixes from DEVICE_ID, SLITBLOCK_ID, and BLOCKFIBER_ID so that they can be treated as integers (this is what desimodel does).

**Comment by sbailey** [comment]
Correction: desimodel keeps the DEVICE_ID as a string, not int, but it does convert SLITBLOCK_ID and BLOCKFIBER_ID to ints.

**Comment by julienguy** [comment]
I had forgotten to commit the changes to README.rst that give the provenance (but did so before your message!). This file is a direct copy. I would like to keep it that way so anyone can verify the source. Only copy the columns DEVICE_ID,PETAL_ID,BUS_ID,CAN_ID from this file are copied in the fp-metrology.csv file. I am keeping the DEVICE_ID name as is because this is how the positioners are identified in the positioner moves and positioner calibration database tables. I do not need  SLITBLOCK_ID and BLOCKFIBER_ID for desimeter, but I can add those columns as well if needed.

**Comment by sbailey** [comment]
OK, that all sounds fine; direct copy is good.  No need to propagate SLITBLOCK_ID and BLOCKFIBER_ID into the final metrology file since you don't need them there.

**Comment by daqiii** [comment]
Stephen,
the index files are in the (online) PositionerIndexTable product in svn. It’s versioned and managed by is.
This is the agreed upon online version of the UMT (but without all the coordinated) and maybe a few more indexes that are not part of the UMT.
I hear you about the letters in DEVICE_ID and such but for the KPNO environment we accepted it so it’s too late to change. (we can argue forever that this whole indexing stuff should be thrown out – mistakes were made, what can I say)

So, for offline you can do what you need to do but for anything that runs as part of the online system it needs to run using this file. IN fact, Julien and I discussed that for the parts of desimeter that will run online he will retrieve the relevant information from the same source as the online system (and not a previously made snapshot conf. file). I gave Julien a sample script and it’s pretty straightforward. But it adds additional dependencies so I understand why Julien picked the snapshot route for now.

Cheers
Klaus

**Comment by sbailey** [comment]
@daqiii (Klaus) that's fine, I'm not advocating changing str/int for the online environment.  Having desimeter use the same file as online without modification (albeit with copy for convenience) is good.

**Pull request merged**
