### PR TITLE
Fit guide star coordinates

### PR DESCRIPTION
**Pull request by julienguy**
Add script to fit GFA guide star catalogs matched to GAIA from Aaron and save resulting transfo in json file.
Example
`
desi_fit_guide_star_coordinates -i guide-00038408_catalog-00000.fits --fits-header guide-00038408_reduced-00000.fits -o toto.json --plot
`
Result
`
{"sxx": 0.9992725875370626, "syy": 0.9991839191429779, "sxy": 4.842950295522175e-05, "tel_ra": 153.69875888354494, "tel_dec":
 39.89856062957868, "fieldrot_deg": -0.12740372516720347, "nstars": 37, "rms_arcsec": 0.46975231417406493}
`
This transformation can then be used to convert the fiber positions from focal plane coordinates to RA,Dec and compare with the design values from the fiberassign files.

### CODE REVIEW

**Comment by sbailey** [comment]
+1 for this script, but the core functionality of fitting for the telescope offset, rotation, and scale should be in a function so that is can be used independently of the script for both analysis and operations.  Please either:
* go ahead and merge this now and open an issue about moving the telescope fitting into a function; or
* move it into a function that the script calls, and then merge

**Comment by julienguy** [comment]
I am still working on the code restructuration

**Comment by julienguy** [comment]
Added FieldModel class that contains the tangent plane transformation correction fitted on the guide stars. The transformation contains
 - actual telescope pointing RA Dec
 - measured field rotation
 - 3 parameter dilatation (sxx,syy,sxy)
 - also save MJD,LST, and hexapod rotation angle

The class contains fp2radec and radec2fp functions which is what we need to compute fiber sky coordinates, and compare with assignments and dithers tests.

Example:
```
desi_fit_guide_star_coordinates -i guide-00038408_catalog-00000.fits --fits-header guide-00038408_reduced-00000.fits -o toto.json
```

Result

```
{"name": "Field model", "version": "1", "ra": 153.17932098471252, "dec": 40.1022
6897789558, "mjd": 58855.39987335368, "lst": 138.6240026880987, "hexrot_deg": 0.
0, "sxx": 1.00072783389296, "syy": 1.0008168468014436, "sxy": -4.840852835607178
6e-05, "fieldrot_deg": -0.060065759423746715, "expid": 0, "nstars": 37, "rms_arc
sec": 0.47013457641909245}
```

**Comment by julienguy** [comment]
Other example, now at KPNO
```
bash
source /software/datasystems/users/jguy/setup.sh
desi_fit_guide_star_coordinates -i  ~/users/ameisner/reduced/realtime/20200119/00042160/gfa-00042160_catalog.fits --fits-header /exposures/desi/20200119/00042160/gfa-00042160.fits.fz -o fp-00042160.json

INFO:fieldmodel.py:161:fit_tancorr:RMS coord. residual = 0.48 arcsec
INFO:fieldmodel.py:162:fit_tancorr:Rotation angle=-0.006 deg
INFO:fieldmodel.py:163:fit_tancorr:Pointing correction dHA=907.69 arcsec, dDec=-308.89 arcsec
INFO:fieldmodel.py:164:fit_tancorr:Scales sxx=1.0006 syy=1.0006 sxy=-0.0000

```

**Comment by julienguy** [comment]
Good to go for me.
After debugging a dependence of fieldrot on the pointing offset, the same example at KPNO,
```
desi_fit_guide_star_coordinates -i  /n/home/datasystems/users/ameisner/reduced/realtime/20200119/00042160/gfa-00042160_catalog.fits --fits-header /exposures/desi/20200119/00042160/gfa-00042160.fits.fz -o fp-00042160.json

INFO:fieldmodel.py:169:fit_tancorr:RMS coord. residual = 0.48 arcsec
INFO:fieldmodel.py:170:fit_tancorr:Rotation angle=0.151 deg
INFO:fieldmodel.py:171:fit_tancorr:Pointing correction dHA=-0.00 arcsec, dDec=0.00 arcsec
INFO:fieldmodel.py:172:fit_tancorr:Scales sxx=1.0006 syy=1.0006 sxy=-0.0000

cat fp-00042160.json

{"name": "Field model", "version": "1", "ra": 39.35752368046017, "dec": 31.986592221730184, "mjd": 58868.10846191641, "lst": 46.24207223439589, "hexrot_deg": 0.0, "sxx": 1.0005959325718503, "syy": 1.0006131671433673, "sxy": -4.272787672534965e-05, "fieldrot_deg": 0.15140722930661538, "expid": 0, "nstars": 162, "rms_arcsec": 0.48302764988814195}

```

**Pull request merged**
