### PR TITLE
Fix get posmoves merge

### PR DESCRIPTION
**Pull request by joesilber**
Fix for get_posmoves --merged feature.
For when vstack on tables that have either no data or slightly different data types.
Astropy is quite intolerant of such situations, so this addresses.

### CODE REVIEW

**Comment by joesilber** [comment]
Example call:
``` get_posmoves --host beyonce.lbl.gov --port 5432 --password reader --exposure-ids 3522 --petal-ids 0 -c -t -o ~/jhsilber/posmovedata/expid_3522 -m```

**Comment by julienguy** [comment]
Does not work with option -c.

**Comment by joesilber** [comment]
Merge now works without the `-c` option.

Note I merged latest master code into this branch, though I probably didn't need to. It was just stale so I wanted to make sure I was testing against all the latest.

**Review by julienguy — APPROVED** [review]
good

**Pull request merged**
