### PR TITLE
Posparams covariance

### PR DESCRIPTION
**Pull request by julienguy**
Adding covariance to the output parameters of fit_posparams in compliance with https://docs.google.com/document/d/1-_OdDwGg889rqjNpbtxNzmn1RTHPfg44HlzwGmHBUIM/edit#

Among several choices, I resorted to 
- save covariances as new columns "COV.PAR1.PAR2"
- no duplicate "COV.PAR2.PAR1" (less space on disk, but need to test both keys when trying to retrieve a covariance)
- replace the variance terms "COV.PAR1.PAR1" by square root as column "ERR.PAR1" (more convenient for plots and shorter)
- remove all columns with null covariance because one parameter is fixed
- keep the ERR.PAR1 column with value = 0 when parameters are fixed to have a mean to get the list of fixed parameters

If no uncertainties on the positions are given (which is the case for now), the default consists in using the rms of the residuals to the fit as uncertainties on the measurements to determine the parameters uncertainties.
The covariance is based on numeric derivatives of the chi2 done in the routine `scipy.optimize.minimize`. I am not familiar with this so I don't know how accurate the covariances will be. We'll have to study this a bit more.

### CODE REVIEW

**Comment by joesilber** [comment]
Error at:
https://app.codacy.com/gh/desihub/desimeter/file/45481835469/issues/source?fileBranchId=18566628#l156

**Comment by joesilber** [comment]
Can the modified fitter be called such that it uses the older algorithm that I had written? Do we have quantitative demonstration that the new one works better?

**Comment by julienguy** [comment]
> Can the modified fitter be called such that it uses the older algorithm that I had written? Do we have quantitative demonstration that the new one works better?

If you have in mind the fit of circles to initiate your fit, this was in a previous PR and it indeed helped recover a many failed fits while not introducing new ones. Now I can add an option to not do this initialization if you want.

**Comment by joesilber** [comment]
Yes, that's what I was wondering. I read the code more careful and see that you're only doing circle fits to find offset_x and offset_y. I was worried if we were trying to do circle fits on the phi arcs, which I think are a scary / noisy path to follow.

**Pull request merged**
