### PR TITLE
Pos analysis readme

### PR DESCRIPTION
**Pull request by joesilber**
First draft at a readme page describing overall positioner analysis workflow. Responds to issue #67.

### CODE REVIEW

**Comment by julienguy** [comment]
Please merge with (or incorporate info from and then remove) other readme file posmov.rst that addresses some of the same aspects.

**Comment by joesilber** [comment]
> 
> 
> Please merge with (or incorporate info from and then remove) other readme file posmov.rst that addresses some of the same aspects.

I am leaving posmov.rst as-is right now, with a link to it.

**Comment by joesilber** [comment]
This PR should be merged now if you are ok with it

**Comment by joesilber** [comment]
> 
> 
> Merging for now but will need some update/cleanup.
> 
>     * we need to update the script get_posmov_fvc_data  to use the exposure ids and exposure iters instead of time stamps

Yes

> 
>     * need to update plotters. for instance is plot_posparams used?

Yes, this is a nice plotter when using fit_posparams in the windowed history / binning mode. I think if we split fit_posparams in two, then it would be natural to make plot_posparams go with the "history" version

> 
>     * also is get_posparams used?

I haven't been using it, but if it still works it seems sort of generically useful. Maybe it is superseded since you started pulling the calibration values into get_posmoves?

**Pull request merged**
