### PR TITLE
Petal1 metrology

### PR DESCRIPTION
**Pull request by julienguy**
- add metrology of petal 1 from DESI-5421 v8
 - add DEVICE_ID and BUS_ID in metrology for convenience 
 - simplify fvc2fp code (no subdirectory, base class, poly2d transfo)
 - improve once again the ZB transfo fit
 - add option `--no-zbfit` on `desi_fvc_proc` to fit just the shift,scale,rotation using pre-existing ZB coeffs.
 - add script `desi_fit_fvc2fp_using_theta_centers` to read several circles csv files (output of desi_fit_circles) to fit high degree ZB coeffs on positioner theta axis center metrology.
 
Example on current petal 1 data:

`desi_fit_fvc2fp_using_theta_centers -i circles-00001* -o toto.json --plot`

One can see the fiducials metrology does not agree well with the positioners metrology. This still has to be sorted out.

theta-centers

### CODE REVIEW

**Comment by julienguy** [comment]
This transform fitted on the theta centers compared to metrology has been saved to `py/desimeter/data/lbl-petal1/init-fvc2fp.json`. The ZB coefficients can then be kept fixed when fitting a FVC image, with the option `desi_fvc_proc --no-zbfit ...`. Doing this on a series of FVC images, and then refitting the circle centers, gives the following residuals between theta centers and metrology. The disagreement on the left of the wedge is due to inconsistencies of the metrology of theta centers and the left most fiducial (that is part of the fit of the fvc2fp transformation (translation,scale,rotation with fixed ZB coeffs).
Figure_2

So we have to decide which one is correct: positioner or fiducial metrology.

**Comment by sbailey** [comment]
This looks fine to me, including committing to a single form of Zhao-Burge based fvc2fp instead of the more generic structure.

@dstndstn can we change the coadacy and coveralls settings to make recommendations but not actually flag PRs with test failures due to trailing whitespace or 1% coverage drops?

**Comment by julienguy** [comment]
codacy is great. it has several levels of issues and the PR was flagged as bad for a very good reason (I had a function duplicated in the code by mistake). so I suggest we don't change the codacy settings (in fact if you go to the 'Details' link you will find many other suggestions).

but coveralls reporting a failure when this is just a low test coverage issue is indeed inconvenient.

**Comment by dstndstn** [comment]
I tried turning off coverall's "status api" feature, so in future it shouldn't show up as a "failure".

Codacy can be obnoxious on occasion (eg if you fix three errors but add one, I think it scolds you), but overall I find it helpful -- just don't take it personally when it emails you to say your PR isn't up to standards!!

**Pull request merged**
