### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by dkirkby**
This is a one-line fix to correct a typo in my earlier PR #189.

### CODE REVIEW

**Comment by dkirkby** [comment]
One CI test is failing on python 3.8 but passing on 3.6 and 3.7:
```
FAIL: test_tan2radec (desimeter.test.test_radec2tan.TestRADEC2TAN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/py/desimeter/test/test_radec2tan.py", line 139, in test_tan2radec
    assert(np.abs(ddec*3600.)<0.001) # 1 milli-arcsec
```
Is this a known problem @sbailey @julienguy ?

**Comment by sbailey** [comment]
The radec2tan failure is not a known issue (to me).  FWIW, it also passes with python 3.9 on my laptop.  @dkirkby or @julienguy could you try creating a py3.8 environment locally and see if it fails for you, or if it is something specific to our circleci py3.8 environment?

**Comment by dkirkby** [comment]
Can we merge this 1-line typo fix now @sbailey then create a new issue to track down the (unrelated) CI test problem?

**Comment by sbailey** [comment]
Thanks for the reminder; yes let's merge this now.  @dkirkby please file a ticket and investigate the radec2tan test failure.

**Pull request merged**
