### PR TITLE
xytest analysis

### PR DESCRIPTION
**Pull request by joesilber**
This script reads in data gathered from the online DB using `get_posmoves`. It can accept a data set comprising one or many exposure ids. In other words, it can analyze one "xytest", yes, but will just as happily analyze performance data for example from one or many nights of observing. Then it calculates the positioning errors and generates several outputs.

CSV outputs:
- **moves** ... all the error data for every move, and submoves identified
- **stats_by_positioner** ... max, min, median, rms etc error performance for each positioner
- **stats_summary** ... overall max, min, median, rms etc errors for the data set

Plot outputs:
- **chart** ... a big xy scatter plot per submove, showing all targets and measurements. Image resolution is automatically scaled. I think this has proven to be the most useful view --- instead of thousands different plot files (one for each positioner), you have a big chart that you can quickly scroll around and see issues
- **histogram** ... one per submove, showing all the errors in the data set

This is a good feature set, for me to start anticollision testing and get rapid feedback on the results. I therefore think this is a good version to push to master. Some future features it could include are:
- more multiprocessing if necessary
- options to filter down which positioner IDs get plotted / analyzed
- comparison of measured results with simulated values from anticollision harness

Additionally, the code is reasonably well factored into functions, but for simplicity right now I kept all the functions in one script file. Future versions could fairly easily push these functions into separate modules --- if we see any value in their re-use.

### CODE REVIEW

**Comment by julienguy** [comment]
code requires numpy version >= 1.15 because of the use of numpy.quantile.
I had numpy 1.14 and updated to 1.18 to be able to run this.

I guess it's fine, but I'd like to give first @sbailey and/or @weaverba137 a chance to comment.

**Comment by sbailey** [comment]
I'm fine with numpy>=1.15 requirement; current desiconda release at NERSC uses numpy 1.19.1.  Functionality sounds great.

**Comment by julienguy** [comment]
do we have to edit the requirements.txt file? If yes, is numpy>=1.15 the correct format?

**Comment by weaverba137** [comment]
Yes that should be the correct format.

**Pull request merged**
