### PR TITLE
Take into account proper motions

### LINKED ISSUE #51: Proper motions
Handle proper motions in desi_fit_guide_stars

### PR DESCRIPTION
**Pull request by segasai**
Fixes #51 

There were some white space auto-formatting changes in the first commit in the branch. I can undo those if needed.

### CODE REVIEW

**Comment by julienguy** [comment]
That's great but next time can you push your branch into this desimeter repo instead of doing a fork. I actually don't know how to checkout out your forked version to test it!

**Comment by segasai** [comment]
Hmm. I thought I followed the standard github practice of feature branch in a clone, followed by a PR. 
You can test my branch by cloning this  https://github.com/segasai/desimeter.git
(I haven't tested the code, as I didn't have a catalog at hand and nersc is down)

**Comment by segasai** [comment]
Okay, got it. I've forgot that I have developer rights here.

**Comment by julienguy** [comment]
It's not crashing because of missing columns. What I suggest is that I copy that part of the code into another branch (without the change of indentation) and with a test of Aaron's catalog that I have on disk. I'll ask you to review this one.

**Comment by segasai** [comment]
okay, it's fine by me.

**Pull request closed without merging**
